[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bier_derive = {path = "../../rpc/bier_derive" }
bierpc = {path = "../../rpc/bierpc" }
protocol = { path = "../protocol" }
clap = "4.6.1"
clap_derive = "4.6.1"
anyhow = "1.0.103"
console = "0.16.4"
tokio = {version = "1.52.3", features = ["full"]}
sysinfo = "0.39.5"
processkit = { version = "2.2.3", features = ["stats"] }
futures = "0.3.32"
gix = { version = "0.84", features = ["blocking-network-client", "blocking-http-transport-reqwest-rust-tls", "worktree-mutation"] }
rand = "0.10.2"
portable-pty = "0.9.0"
tar = "0.4"
flate2 = "1"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Console"] }
