use bierpc::serialize::Serialize;
use bierpc::serialize::Deserialize;
use std::net::{SocketAddr};
use std::path::PathBuf;
use bier_derive::{Deserialize, Serialize};
use tokio::fs;

/// The persisted instance definition is the same type the client sends.
pub use protocol::instance::InstanceConfig;

#[derive(Serialize, Deserialize, Clone)]
pub struct ServerStg {
    pub addr: SocketAddr,
    pub config_path: PathBuf,
    pub storage_path: PathBuf,
    /// Roots (besides the instances dir) that file upload/download may touch.
    pub file_roots: Vec<PathBuf>,
    /// How long a terminal/file-transfer session offer stays connectable.
    pub session_ttl_secs: u64,
    /// Shell spawned for terminal Shell sessions.
    pub shell: String,
    /// Pre-shared authentication key; every request must be signed with it.
    /// See `protocol::auth`. Generated by `server keygen`.
    pub key: Vec<u8>,
    /// Whether `Action::Bootstrap` may hand this server over to itself.
    pub bootstrap: bool,
}

pub fn default_shell() -> String {
    if cfg!(windows) { "cmd.exe".to_string() } else { "/bin/sh".to_string() }
}

impl ServerStg {
    pub fn instances_index_path(&self) -> PathBuf {
        self.storage_path.join("instances.chld")
    }

    pub fn instances_dir(&self) -> PathBuf {
        self.storage_path.join("instances")
    }

    pub fn instance_dir(&self, id: u128) -> PathBuf {
        self.instances_dir().join(format!("{:032x}", id))
    }

    pub fn repo_dir(&self, id: u128) -> PathBuf {
        self.instance_dir(id).join("repo")
    }

    pub async fn new(
        addr: SocketAddr,
        config_path: PathBuf,
        storage_path: PathBuf,
        file_roots: Vec<PathBuf>,
        session_ttl_secs: u64,
        shell: String,
        key: Vec<u8>,
        bootstrap: bool,
    ) -> anyhow::Result<(Self, Vec<InstanceConfig>)> {
        if config_path.exists() {
            fs::remove_file(&config_path).await?;
        }
        fs::create_dir_all(&storage_path).await?;
        let ft = Self {
            addr,
            config_path,
            storage_path,
            file_roots,
            session_ttl_secs,
            shell,
            key,
            bootstrap,
        };
        fs::create_dir_all(ft.instances_dir()).await?;
        ft.save().await?;
        let instances = ft.load_instances().await?;
        Ok((ft, instances))
    }

    pub async fn save(&self) -> anyhow::Result<()> {
        let mut f = fs::File::options()
            .create(true).truncate(true).write(true)
            .open(&self.config_path).await?;
        self.serialize(&mut f).await?;
        use tokio::io::AsyncWriteExt;
        f.flush().await?;
        Ok(())
    }

    pub async fn load(config_path: PathBuf) -> anyhow::Result<(Self, Vec<InstanceConfig>)> {
        let mut f = fs::File::options().read(true).open(&config_path).await?;
        let ft = ServerStg::deserialize(&mut f).await?;
        if ft.key.len() != protocol::auth::KEY_LEN {
            anyhow::bail!(
                "this config has no usable authentication key — run `server -c {} keygen <phrase>`",
                config_path.display(),
            );
        }
        fs::create_dir_all(ft.instances_dir()).await?;
        let instances = ft.load_instances().await?;
        Ok((ft, instances))
    }

    pub async fn load_instances(&self) -> anyhow::Result<Vec<InstanceConfig>> {
        let path = self.instances_index_path();
        if path.exists() {
            let mut file = fs::File::open(path).await?;
            Ok(Vec::<InstanceConfig>::deserialize(&mut file).await?)
        } else {
            Ok(Vec::new())
        }
    }

    /// Atomically rewrite the instance index (write temp file, then rename).
    pub async fn save_instances(&self, instances: &Vec<InstanceConfig>) -> anyhow::Result<()> {
        let path = self.instances_index_path();
        let tmp = path.with_extension("chld.tmp");
        {
            let mut f = fs::File::options().create(true).truncate(true).write(true).open(&tmp).await?;
            instances.serialize(&mut f).await?;
            use tokio::io::AsyncWriteExt;
            f.flush().await?;
        }
        if path.exists() {
            fs::remove_file(&path).await?;
        }
        fs::rename(&tmp, &path).await?;
        Ok(())
    }
}
